### ISSUE TITLE
statrs kernel density estimation

### ISSUE THREAD

**Issue by wangjiawen2013** [seatonullberg/kernel-density-estimation#5]
Hi,
statrs is lack of kernel density estimation tools. Could you help ?
https://github.com/statrs-dev/statrs/issues/193

**Comment by seatonullberg** [comment]
What sort of help is needed? This implementation is currently incomplete, but I plan to build out multivariate estimation and add more kernel functions. I would rather focus my efforts on making those changes to this crate instead of building a separate implementation in statrs. I'm happy to answer any questions the authors may have though.
